<?php

$sLangName = 'Deutsch';

$aLang = [
    'charset' => 'UTF-8',

    'FOUN10_DASHBOARD_LOCALE' => 'de-DE',
    'FOUN10_DASHBOARD_TITLE' => 'Dashboard',
    'FOUN10_DASHBOARD_REVENUE_NOTE' => 'Netto-Warenumsatz in der Standardwährung nach Rabatten, ohne Versand- und Zahlungskosten – Fremdwährungen zum Kurs der Bestellung umgerechnet. Ohne stornierte und nicht abgeschlossene Bestellungen',
    'FOUN10_DASHBOARD_GENERATED_AT' => 'Stand',
    'FOUN10_DASHBOARD_REFRESH' => 'Aktualisieren',

    'FOUN10_DASHBOARD_PERIOD' => 'Zeitraum',
    'FOUN10_DASHBOARD_PERIOD_TODAY' => 'Heute',
    'FOUN10_DASHBOARD_PERIOD_7D' => '7 Tage',
    'FOUN10_DASHBOARD_PERIOD_30D' => '30 Tage',
    'FOUN10_DASHBOARD_PERIOD_90D' => '90 Tage',
    'FOUN10_DASHBOARD_PERIOD_YTD' => 'Seit Jahresbeginn',
    'FOUN10_DASHBOARD_PERIOD_CUSTOM' => 'Zeitraum',
    'FOUN10_DASHBOARD_RANGE_FROM' => 'Von',
    'FOUN10_DASHBOARD_RANGE_TO' => 'Bis',
    'FOUN10_DASHBOARD_RANGE_APPLY' => 'Anzeigen',

    'FOUN10_DASHBOARD_KPI_REVENUE' => 'Umsatz netto',
    'FOUN10_DASHBOARD_KPI_ORDERS' => 'Bestellungen',
    'FOUN10_DASHBOARD_KPI_AVERAGE' => 'Ø Bestellwert',
    'FOUN10_DASHBOARD_KPI_NEW_CUSTOMERS' => 'Neue Kundenkonten',
    'FOUN10_DASHBOARD_VS_PREVIOUS' => 'ggü. Vorperiode',
    'FOUN10_DASHBOARD_VS_LAST_YEAR' => 'ggü. Vorjahr',
    'FOUN10_DASHBOARD_PREVIOUS_PERIOD' => 'Vorperiode',

    'FOUN10_DASHBOARD_TREND_TITLE' => 'Umsatzverlauf',
    'FOUN10_DASHBOARD_TREND_TITLE_ORDERS' => 'Bestellverlauf',
    'FOUN10_DASHBOARD_TREND_METRIC' => 'Kennzahl im Diagramm',
    'FOUN10_DASHBOARD_METRIC_REVENUE' => 'Umsatz',
    'FOUN10_DASHBOARD_CUMULATIVE' => 'Kumuliert',
    'FOUN10_DASHBOARD_CUMULATIVE_UNTIL' => 'Summe bis',
    'FOUN10_DASHBOARD_TREND_BUCKET_HOUR' => 'pro Stunde, verglichen mit demselben Tag im Vorjahr',
    'FOUN10_DASHBOARD_TREND_BUCKET_DAY' => 'pro Tag, verglichen mit denselben Tagen im Vorjahr',
    'FOUN10_DASHBOARD_TREND_BUCKET_WEEK' => 'pro Kalenderwoche, verglichen mit derselben Kalenderwoche im Vorjahr',
    'FOUN10_DASHBOARD_TREND_BUCKET_MONTH' => 'pro Monat, verglichen mit demselben Monat im Vorjahr',
    'FOUN10_DASHBOARD_SERIES_CURRENT' => 'Aktueller Zeitraum',
    'FOUN10_DASHBOARD_SERIES_LAST_YEAR' => 'Vorjahr',
    'FOUN10_DASHBOARD_SHOW_TABLE' => 'Als Tabelle anzeigen',
    'FOUN10_DASHBOARD_YEARLY_TITLE' => 'Jahresvergleich',
    'FOUN10_DASHBOARD_YEARLY_HINT' => 'Pro Monat, unabhängig vom gewählten Zeitraum. Das laufende Jahr nur bis heute.',
    'FOUN10_DASHBOARD_YEARLY_SELECT' => 'Jahre im Diagramm',
    'FOUN10_DASHBOARD_YEARLY_MAX' => 'Höchstens 4 Jahre gleichzeitig – erst ein Jahr abwählen.',
    'FOUN10_DASHBOARD_YEARLY_TO_DATE' => 'bis heute',
    'FOUN10_DASHBOARD_YEARLY_YEAR' => 'Jahr',
    'FOUN10_DASHBOARD_YEARLY_TOTAL' => 'Gesamt',
    'FOUN10_DASHBOARD_YEARLY_BEST' => 'Fett: bester Monatswert über alle Jahre · ▲▼ ggü. demselben Monat im Vorjahr',
    'FOUN10_DASHBOARD_TABLE_DATE' => 'Zeitraum',
    'FOUN10_DASHBOARD_WEEK_SHORT' => 'KW',
    'FOUN10_DASHBOARD_ORDERS_SHORT' => 'Bestellungen',
    'FOUN10_DASHBOARD_ORDERS_ABBR' => 'Best.',

    'FOUN10_DASHBOARD_CUSTOMER_TYPES' => 'Neu- und Stammkunden',
    'FOUN10_DASHBOARD_CUSTOMER_TYPES_HINT' => 'Nach E-Mail-Adresse: Stammkunden hatten schon eine frühere Bestellung.',
    'FOUN10_DASHBOARD_CUSTOMER_TYPE_RETURNING' => 'Stammkunden',
    'FOUN10_DASHBOARD_CUSTOMER_TYPE_NEW' => 'Neukunden mit Konto',
    'FOUN10_DASHBOARD_CUSTOMER_TYPE_GUEST' => 'Neukunden als Gast',
    'FOUN10_DASHBOARD_PAYMENTS' => 'Zahlungsarten',
    'FOUN10_DASHBOARD_COUNTRIES' => 'Lieferländer',
    'FOUN10_DASHBOARD_COUNTRIES_HINT' => 'Land der Lieferadresse, ohne abweichende Lieferadresse das Rechnungsland.',
    'FOUN10_DASHBOARD_OTHER' => 'Weitere',
    'FOUN10_DASHBOARD_UNKNOWN' => 'Unbekannt',
    'FOUN10_DASHBOARD_NO_DATA' => 'Keine Bestellungen in diesem Zeitraum.',

    'FOUN10_DASHBOARD_TOP_SELLERS' => 'Topseller',
    'FOUN10_DASHBOARD_TOP_SELLERS_HINT' => 'Nach verkaufter Menge, Varianten zusammengefasst. Umsatz netto vor Gutscheinen. Bestand = aktueller Lagerbestand aller Varianten.',
    'FOUN10_DASHBOARD_SHOW_MORE' => 'Weitere 10 anzeigen',
    'FOUN10_DASHBOARD_LOADING' => 'Wird geladen …',
    'FOUN10_DASHBOARD_LOAD_ERROR' => 'Laden fehlgeschlagen – erneut versuchen',
    'FOUN10_DASHBOARD_COL_PRODUCT' => 'Artikel',
    'FOUN10_DASHBOARD_COL_QTY' => 'Menge',
    'FOUN10_DASHBOARD_COL_STOCK' => 'Bestand',
    'FOUN10_DASHBOARD_COL_CUSTOMER' => 'Kunde',
    'FOUN10_DASHBOARD_COL_VALUE' => 'Wert',
    'FOUN10_DASHBOARD_COL_CHANGED' => 'Geändert',
    'FOUN10_DASHBOARD_STOCK_SOLD_OUT' => 'Ausverkauft',
    'FOUN10_DASHBOARD_STOCK_PIECES' => 'Stk.',
    'FOUN10_DASHBOARD_VARIANTS_SOLD_OUT' => 'Varianten ausverkauft',
    'FOUN10_DASHBOARD_INACTIVE' => 'inaktiv',
    'FOUN10_DASHBOARD_OPEN_IN_SHOP' => 'Im Shop ansehen (neuer Tab)',
    'FOUN10_DASHBOARD_DELETED' => 'gelöscht',

    'FOUN10_DASHBOARD_BASKETS' => 'Offene Warenkörbe',
    'FOUN10_DASHBOARD_BASKETS_HINT' => 'Letzte 24 Stunden, unabhängig vom gewählten Zeitraum. Nur eingeloggte Kunden – Gast-Warenkörbe werden nicht gespeichert.',
    'FOUN10_DASHBOARD_BASKETS_OPEN' => 'Offen',
    'FOUN10_DASHBOARD_BASKETS_VALUE' => 'Warenwert',
    'FOUN10_DASHBOARD_BASKETS_NONE' => 'Keine offenen Warenkörbe in den letzten 24 Stunden.',
    'FOUN10_DASHBOARD_BASKETS_UNAVAILABLE' => 'Das Speichern von Warenkörben ist in den Shop-Einstellungen abgeschaltet (Stammdaten → Grundeinstellungen → Perform. → „Warenkörbe von angemeldeten Benutzern nicht speichern“).',
    'FOUN10_DASHBOARD_ITEMS' => 'Artikel',
    'FOUN10_DASHBOARD_NET' => 'netto',
    'FOUN10_DASHBOARD_GROSS' => 'brutto',

    'SHOP_MODULE_GROUP_foun10Dashboard' => 'Sales Dashboard',
    'SHOP_MODULE_foun10DashboardCacheTTL' => 'Cache-Dauer der Kennzahlen in Sekunden',
];
