<?php

$sLangName = 'English';

$aLang = [
    'charset' => 'UTF-8',

    'FOUN10_DASHBOARD_LOCALE' => 'en-GB',
    'FOUN10_DASHBOARD_TITLE' => 'Dashboard',
    'FOUN10_DASHBOARD_REVENUE_NOTE' => 'Net goods revenue in the default currency after discounts, excluding shipping and payment costs – other currencies converted at the order’s rate. Cancelled and unfinished orders excluded',
    'FOUN10_DASHBOARD_GENERATED_AT' => 'As of',
    'FOUN10_DASHBOARD_REFRESH' => 'Refresh',

    'FOUN10_DASHBOARD_PERIOD' => 'Period',
    'FOUN10_DASHBOARD_PERIOD_TODAY' => 'Today',
    'FOUN10_DASHBOARD_PERIOD_7D' => '7 days',
    'FOUN10_DASHBOARD_PERIOD_30D' => '30 days',
    'FOUN10_DASHBOARD_PERIOD_90D' => '90 days',
    'FOUN10_DASHBOARD_PERIOD_YTD' => 'Year to date',
    'FOUN10_DASHBOARD_PERIOD_CUSTOM' => 'Period',
    'FOUN10_DASHBOARD_RANGE_FROM' => 'From',
    'FOUN10_DASHBOARD_RANGE_TO' => 'To',
    'FOUN10_DASHBOARD_RANGE_APPLY' => 'Show',

    'FOUN10_DASHBOARD_KPI_REVENUE' => 'Net revenue',
    'FOUN10_DASHBOARD_KPI_ORDERS' => 'Orders',
    'FOUN10_DASHBOARD_KPI_AVERAGE' => 'Avg. order value',
    'FOUN10_DASHBOARD_KPI_NEW_CUSTOMERS' => 'New customer accounts',
    'FOUN10_DASHBOARD_VS_PREVIOUS' => 'vs. previous period',
    'FOUN10_DASHBOARD_VS_LAST_YEAR' => 'vs. last year',
    'FOUN10_DASHBOARD_PREVIOUS_PERIOD' => 'Previous period',

    'FOUN10_DASHBOARD_TREND_TITLE' => 'Revenue trend',
    'FOUN10_DASHBOARD_TREND_TITLE_ORDERS' => 'Order trend',
    'FOUN10_DASHBOARD_TREND_METRIC' => 'Chart metric',
    'FOUN10_DASHBOARD_METRIC_REVENUE' => 'Revenue',
    'FOUN10_DASHBOARD_CUMULATIVE' => 'Cumulative',
    'FOUN10_DASHBOARD_CUMULATIVE_UNTIL' => 'Total up to',
    'FOUN10_DASHBOARD_TREND_BUCKET_HOUR' => 'per hour, compared with the same day last year',
    'FOUN10_DASHBOARD_TREND_BUCKET_DAY' => 'per day, compared with the same days last year',
    'FOUN10_DASHBOARD_TREND_BUCKET_WEEK' => 'per calendar week, compared with the same calendar week last year',
    'FOUN10_DASHBOARD_TREND_BUCKET_MONTH' => 'per month, compared with the same month last year',
    'FOUN10_DASHBOARD_SERIES_CURRENT' => 'Current period',
    'FOUN10_DASHBOARD_SERIES_LAST_YEAR' => 'Last year',
    'FOUN10_DASHBOARD_SHOW_TABLE' => 'Show as table',
    'FOUN10_DASHBOARD_YEARLY_TITLE' => 'Yearly comparison',
    'FOUN10_DASHBOARD_YEARLY_HINT' => 'Per month, independent of the selected period. The current year up to today only.',
    'FOUN10_DASHBOARD_YEARLY_SELECT' => 'Years in the chart',
    'FOUN10_DASHBOARD_YEARLY_MAX' => 'At most 4 years at once – deselect a year first.',
    'FOUN10_DASHBOARD_YEARLY_TO_DATE' => 'to date',
    'FOUN10_DASHBOARD_YEARLY_YEAR' => 'Year',
    'FOUN10_DASHBOARD_YEARLY_TOTAL' => 'Total',
    'FOUN10_DASHBOARD_YEARLY_BEST' => 'Bold: best value of the month across all years · ▲▼ vs. the same month a year earlier',
    'FOUN10_DASHBOARD_TABLE_DATE' => 'Period',
    'FOUN10_DASHBOARD_WEEK_SHORT' => 'Wk',
    'FOUN10_DASHBOARD_ORDERS_SHORT' => 'orders',
    'FOUN10_DASHBOARD_ORDERS_ABBR' => 'ord.',

    'FOUN10_DASHBOARD_CUSTOMER_TYPES' => 'New and returning customers',
    'FOUN10_DASHBOARD_CUSTOMER_TYPES_HINT' => 'By e-mail address: returning customers had an earlier order.',
    'FOUN10_DASHBOARD_CUSTOMER_TYPE_RETURNING' => 'Returning customers',
    'FOUN10_DASHBOARD_CUSTOMER_TYPE_NEW' => 'New, with account',
    'FOUN10_DASHBOARD_CUSTOMER_TYPE_GUEST' => 'New, as guest',
    'FOUN10_DASHBOARD_PAYMENTS' => 'Payment methods',
    'FOUN10_DASHBOARD_COUNTRIES' => 'Delivery countries',
    'FOUN10_DASHBOARD_COUNTRIES_HINT' => 'Country of the delivery address, the billing country if no separate delivery address was given.',
    'FOUN10_DASHBOARD_OTHER' => 'Other',
    'FOUN10_DASHBOARD_UNKNOWN' => 'Unknown',
    'FOUN10_DASHBOARD_NO_DATA' => 'No orders in this period.',

    'FOUN10_DASHBOARD_TOP_SELLERS' => 'Top sellers',
    'FOUN10_DASHBOARD_TOP_SELLERS_HINT' => 'By quantity sold, variants combined. Net revenue before vouchers. Stock = current stock of all variants.',
    'FOUN10_DASHBOARD_SHOW_MORE' => 'Show 10 more',
    'FOUN10_DASHBOARD_LOADING' => 'Loading …',
    'FOUN10_DASHBOARD_LOAD_ERROR' => 'Loading failed – try again',
    'FOUN10_DASHBOARD_COL_PRODUCT' => 'Product',
    'FOUN10_DASHBOARD_COL_QTY' => 'Qty',
    'FOUN10_DASHBOARD_COL_STOCK' => 'Stock',
    'FOUN10_DASHBOARD_COL_CUSTOMER' => 'Customer',
    'FOUN10_DASHBOARD_COL_VALUE' => 'Value',
    'FOUN10_DASHBOARD_COL_CHANGED' => 'Changed',
    'FOUN10_DASHBOARD_STOCK_SOLD_OUT' => 'Sold out',
    'FOUN10_DASHBOARD_STOCK_PIECES' => 'pcs',
    'FOUN10_DASHBOARD_VARIANTS_SOLD_OUT' => 'variants sold out',
    'FOUN10_DASHBOARD_INACTIVE' => 'inactive',
    'FOUN10_DASHBOARD_OPEN_IN_SHOP' => 'View in shop (new tab)',
    'FOUN10_DASHBOARD_DELETED' => 'deleted',

    'FOUN10_DASHBOARD_BASKETS' => 'Open baskets',
    'FOUN10_DASHBOARD_BASKETS_HINT' => 'Last 24 hours, independent of the selected period. Logged-in customers only – guest baskets are not stored.',
    'FOUN10_DASHBOARD_BASKETS_OPEN' => 'Open',
    'FOUN10_DASHBOARD_BASKETS_VALUE' => 'Goods value',
    'FOUN10_DASHBOARD_BASKETS_NONE' => 'No open baskets in the last 24 hours.',
    'FOUN10_DASHBOARD_BASKETS_UNAVAILABLE' => 'Basket saving is switched off in the shop settings (Master Settings → Core Settings → Perform. → “Don’t save Shopping Carts of registered Users”).',
    'FOUN10_DASHBOARD_ITEMS' => 'items',
    'FOUN10_DASHBOARD_NET' => 'net',
    'FOUN10_DASHBOARD_GROSS' => 'gross',

    'SHOP_MODULE_GROUP_foun10Dashboard' => 'Sales Dashboard',
    'SHOP_MODULE_foun10DashboardCacheTTL' => 'Cache lifetime of the figures in seconds',
];
